# Generated by Django 3.2.9 on 2021-12-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='introduction',
            new_name='location',
        ),
    ]
